Repository mszostok/codeowners-validator, pull requests merged in 2020-10, with the labels that each got.

#43 Add unit-tests coverage for dup_pattern checker
  go.mod
  go.sum
  internal/check/duplicated_pattern.go
  internal/check/duplicated_pattern_test.go
  internal/check/helpers_test.go
  internal/context/check_test.go
  internal/envconfig/envconfig_test.go
  internal/github/client.go
  pkg/codeowners/owners.go
  tests/integration/integration_test.go
Labels: enhancement

#44 Fix file exists checker
  .travis.yml
  Makefile
  docs/investigation/file_exists_checker/file_matcher_libs_bench_test.go
  docs/investigation/file_exists_checker/glob.md
  docs/investigation/file_exists_checker/go.mod
  docs/investigation/file_exists_checker/go.sum
  go.mod
  go.sum
  hack/ci/run-lint.sh
  internal/check/api.go
  internal/check/duplicated_pattern.go
  internal/check/file_exists.go
  internal/check/file_exists_test.go
  internal/check/helpers_test.go
  internal/check/not_owned_file.go
  internal/check/valid_owner.go
  internal/ptr/uint.go
  internal/runner/runner_worker.go
Labels: bug, documentation

#45 Add dockerfile and shellcheck linters, refactor hack dir
  .golangci.yml
  .travis.yml
  Dockerfile
  Makefile
  hack/README.md
  hack/ci/compress.sh
  hack/ci/run-lint.sh
  hack/ci/run-test-integration.sh
  hack/ci/run-test-unit.sh
  hack/compress.sh
  hack/lib/utilities.sh
  hack/run-lint.sh
  hack/run-test-integration.sh
  hack/run-test-unit.sh
  internal/check/duplicated_pattern.go
  internal/check/duplicated_pattern_test.go
  internal/check/file_exists.go
  internal/check/not_owned_file.go
  internal/check/valid_owner.go
  internal/ctxutil/check.go
  internal/ctxutil/check_test.go
  pkg/version/base.go
Labels: enhancement

#47 Fix report badge link
  README.md
Labels: bug, documentation

#48 Add test coverage for checks
  internal/check/api.go
  internal/check/api_test.go
  internal/check/file_exists_test.go
  internal/check/package_test.go
  internal/printer/testdata/TestTTYPrinterPrintCheckResult/Should_print_OK_status_on_empty_issues_list.golden.txt
  internal/printer/testdata/TestTTYPrinterPrintCheckResult/Should_print_all_reported_issues.golden.txt
  internal/printer/testdata/TestTTYPrinterPrintSummary/Should_print_'no'_when_there_is_no_failures.golden.txt
  internal/printer/testdata/TestTTYPrinterPrintSummary/Should_print_number_of_failures.golden.txt
  internal/printer/tty.go
  internal/printer/tty_test.go
Labels: enhancement

#56 Add CONTRIBUTING.md and development.md
  .github/ ISSUE_TEMPLATE/bug-report.md
  .github/ ISSUE_TEMPLATE/feature-request.md
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/development.md
Labels: documentation, enhancement
