Repository mszostok/codeowners-validator, pull requests merged in 2022-04, with the labels that each got.

#137 Add missing cfg in action.yml, add missing test for 'OwnersMustBeTeams' check
  README.md
  action.yml
  docs/gh-action.md
  internal/check/valid_owner.go
  internal/check/valid_owner_test.go
Labels: enhancement

#143 Add token validation when necessary, fmt shell code, enable 'gocritics'
  .github/workflows/pull-requests.yml
  .golangci.yml
  hack/compress.sh
  hack/run-lint.sh
  hack/run-test-integration.sh
  hack/run-test-unit.sh
  internal/check/file_exists_test.go
  internal/check/not_owned_file.go
  internal/check/valid_owner.go
  internal/github/client.go
  internal/load/load.go
  main.go
  pkg/codeowners/owners.go
  pkg/version/version.go
  tests/integration/helpers_test.go
  tests/integration/integration_test.go
  tests/integration/testdata/TestOwnerCheckAuthZAndAuthN/invalid_token_specified.golden.txt
  tests/integration/testdata/TestOwnerCheckAuthZAndAuthN/token_not_specified.golden.txt
  tests/integration/testdata/TestOwnerCheckAuthZAndAuthN/token_specified_but_without_necessary_scopes.golden.txt
  tests/integration/testdata/TestOwnerCheckAuthZAndAuthN/token_specified_but_without_necessary_scopes_and_against_private_repo.golden.txt
Labels: enhancement

#145 Fix scope and internal error handling
  internal/check/valid_owner.go
  internal/runner/runner_worker.go
Labels: bug

#146 Support Github App authentication
  .github/workflows/pull-requests.yml
  README.md
  docs/gh-token.md
  go.mod
  go.sum
  internal/check/package_test.go
  internal/check/valid_owner.go
  internal/check/valid_owner_test.go
  internal/github/client.go
  internal/load/load.go
  tests/integration/integration_test.go
  tests/integration/testdata/TestGitHubAppAuth.golden.txt
  tests/integration/testdata/TestOwnerCheckAuthZAndAuthN/token_not_specified.golden.txt
Labels: enhancement

#149 New experimental check: Avoid shadowing
  README.md
  internal/check/avoid_shadowing.go
  internal/check/avoid_shadowing_test.go
  internal/load/load.go
  tests/integration/integration_test.go
  tests/integration/testdata/TestCheckFailures/avoid-shadowing.golden.txt
  tests/integration/testdata/TestCheckSuccess/offline_checks/GitHubCODEOWNERS/avoid-shadowing.golden.txt
  tests/integration/testdata/TestCheckSuccess/offline_checks/gh-codeowners/avoid-shadowing.golden.txt
Labels: enhancement

#153 Update main README.md
  README.md
Labels: documentation

#154 Adjust docs and GitHub action for v0.7.4 release
  README.md
  action.yml
  docs/gh-action.md
Labels: documentation
